### ISSUE TITLE
Error: segmentation fault (when running on MacBook M1)

### ISSUE THREAD

**Issue by fs302** [venomouscyanide/ScaLed#76]
After quick install with quick_install.sh
still can not work on M1 chips using: 
`python seal_link_pred.py --dataset USAir --epochs 50 --num_hops 2 --seed 1 --profile`

**Comment by fs302** [comment]
Thanks for reply. I did as you said:
1. update llvm and redirect CC=/opt/homebrew/Cellar/llvm/15.0.5/bin/clang
2. del profile argument, with `python seal_link_pred.py --dataset USAir --epochs 50 --num_hops 2 --seed 1`
3. reinstall dependencies as you listed

but it fails again. PS: origin SEAL works on my Mac.

Well, I will try other methods to fix this prob, and share that if it works.

**Comment by venomouscyanide** [comment]
Thanks for the update. Please let us know.

**Comment by venomouscyanide** [comment]
Closing stale issue. However, please feel free to continue the discussion here.
